// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: snowowl.proto

#include "snowowl.pb.h"
#include "snowowl.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace snowowl {

static const char* DeviceService_method_names[] = {
  "/snowowl.DeviceService/ListDevices",
  "/snowowl.DeviceService/GetDevice",
  "/snowowl.DeviceService/CreateDevice",
  "/snowowl.DeviceService/UpdateDevice",
  "/snowowl.DeviceService/DeleteDevice",
  "/snowowl.DeviceService/StreamDeviceEvents",
};

std::unique_ptr< DeviceService::Stub> DeviceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DeviceService::Stub> stub(new DeviceService::Stub(channel, options));
  return stub;
}

DeviceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListDevices_(DeviceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDevice_(DeviceService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateDevice_(DeviceService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateDevice_(DeviceService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteDevice_(DeviceService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamDeviceEvents_(DeviceService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status DeviceService::Stub::ListDevices(::grpc::ClientContext* context, const ::snowowl::ListDevicesRequest& request, ::snowowl::ListDevicesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snowowl::ListDevicesRequest, ::snowowl::ListDevicesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListDevices_, context, request, response);
}

void DeviceService::Stub::async::ListDevices(::grpc::ClientContext* context, const ::snowowl::ListDevicesRequest* request, ::snowowl::ListDevicesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snowowl::ListDevicesRequest, ::snowowl::ListDevicesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListDevices_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::ListDevices(::grpc::ClientContext* context, const ::snowowl::ListDevicesRequest* request, ::snowowl::ListDevicesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListDevices_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snowowl::ListDevicesResponse>* DeviceService::Stub::PrepareAsyncListDevicesRaw(::grpc::ClientContext* context, const ::snowowl::ListDevicesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snowowl::ListDevicesResponse, ::snowowl::ListDevicesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListDevices_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snowowl::ListDevicesResponse>* DeviceService::Stub::AsyncListDevicesRaw(::grpc::ClientContext* context, const ::snowowl::ListDevicesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListDevicesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceService::Stub::GetDevice(::grpc::ClientContext* context, const ::snowowl::GetDeviceRequest& request, ::snowowl::GetDeviceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snowowl::GetDeviceRequest, ::snowowl::GetDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDevice_, context, request, response);
}

void DeviceService::Stub::async::GetDevice(::grpc::ClientContext* context, const ::snowowl::GetDeviceRequest* request, ::snowowl::GetDeviceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snowowl::GetDeviceRequest, ::snowowl::GetDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDevice_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::GetDevice(::grpc::ClientContext* context, const ::snowowl::GetDeviceRequest* request, ::snowowl::GetDeviceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDevice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snowowl::GetDeviceResponse>* DeviceService::Stub::PrepareAsyncGetDeviceRaw(::grpc::ClientContext* context, const ::snowowl::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snowowl::GetDeviceResponse, ::snowowl::GetDeviceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDevice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snowowl::GetDeviceResponse>* DeviceService::Stub::AsyncGetDeviceRaw(::grpc::ClientContext* context, const ::snowowl::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDeviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceService::Stub::CreateDevice(::grpc::ClientContext* context, const ::snowowl::CreateDeviceRequest& request, ::snowowl::CreateDeviceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snowowl::CreateDeviceRequest, ::snowowl::CreateDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateDevice_, context, request, response);
}

void DeviceService::Stub::async::CreateDevice(::grpc::ClientContext* context, const ::snowowl::CreateDeviceRequest* request, ::snowowl::CreateDeviceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snowowl::CreateDeviceRequest, ::snowowl::CreateDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateDevice_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::CreateDevice(::grpc::ClientContext* context, const ::snowowl::CreateDeviceRequest* request, ::snowowl::CreateDeviceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateDevice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snowowl::CreateDeviceResponse>* DeviceService::Stub::PrepareAsyncCreateDeviceRaw(::grpc::ClientContext* context, const ::snowowl::CreateDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snowowl::CreateDeviceResponse, ::snowowl::CreateDeviceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateDevice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snowowl::CreateDeviceResponse>* DeviceService::Stub::AsyncCreateDeviceRaw(::grpc::ClientContext* context, const ::snowowl::CreateDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateDeviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceService::Stub::UpdateDevice(::grpc::ClientContext* context, const ::snowowl::UpdateDeviceRequest& request, ::snowowl::UpdateDeviceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snowowl::UpdateDeviceRequest, ::snowowl::UpdateDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateDevice_, context, request, response);
}

void DeviceService::Stub::async::UpdateDevice(::grpc::ClientContext* context, const ::snowowl::UpdateDeviceRequest* request, ::snowowl::UpdateDeviceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snowowl::UpdateDeviceRequest, ::snowowl::UpdateDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateDevice_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::UpdateDevice(::grpc::ClientContext* context, const ::snowowl::UpdateDeviceRequest* request, ::snowowl::UpdateDeviceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateDevice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snowowl::UpdateDeviceResponse>* DeviceService::Stub::PrepareAsyncUpdateDeviceRaw(::grpc::ClientContext* context, const ::snowowl::UpdateDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snowowl::UpdateDeviceResponse, ::snowowl::UpdateDeviceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateDevice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snowowl::UpdateDeviceResponse>* DeviceService::Stub::AsyncUpdateDeviceRaw(::grpc::ClientContext* context, const ::snowowl::UpdateDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateDeviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceService::Stub::DeleteDevice(::grpc::ClientContext* context, const ::snowowl::DeleteDeviceRequest& request, ::snowowl::DeleteDeviceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snowowl::DeleteDeviceRequest, ::snowowl::DeleteDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteDevice_, context, request, response);
}

void DeviceService::Stub::async::DeleteDevice(::grpc::ClientContext* context, const ::snowowl::DeleteDeviceRequest* request, ::snowowl::DeleteDeviceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snowowl::DeleteDeviceRequest, ::snowowl::DeleteDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteDevice_, context, request, response, std::move(f));
}

void DeviceService::Stub::async::DeleteDevice(::grpc::ClientContext* context, const ::snowowl::DeleteDeviceRequest* request, ::snowowl::DeleteDeviceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteDevice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snowowl::DeleteDeviceResponse>* DeviceService::Stub::PrepareAsyncDeleteDeviceRaw(::grpc::ClientContext* context, const ::snowowl::DeleteDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snowowl::DeleteDeviceResponse, ::snowowl::DeleteDeviceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteDevice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snowowl::DeleteDeviceResponse>* DeviceService::Stub::AsyncDeleteDeviceRaw(::grpc::ClientContext* context, const ::snowowl::DeleteDeviceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteDeviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::snowowl::DeviceEvent>* DeviceService::Stub::StreamDeviceEventsRaw(::grpc::ClientContext* context, const ::snowowl::StreamDeviceEventsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::snowowl::DeviceEvent>::Create(channel_.get(), rpcmethod_StreamDeviceEvents_, context, request);
}

void DeviceService::Stub::async::StreamDeviceEvents(::grpc::ClientContext* context, const ::snowowl::StreamDeviceEventsRequest* request, ::grpc::ClientReadReactor< ::snowowl::DeviceEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::snowowl::DeviceEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamDeviceEvents_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::snowowl::DeviceEvent>* DeviceService::Stub::AsyncStreamDeviceEventsRaw(::grpc::ClientContext* context, const ::snowowl::StreamDeviceEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::snowowl::DeviceEvent>::Create(channel_.get(), cq, rpcmethod_StreamDeviceEvents_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::snowowl::DeviceEvent>* DeviceService::Stub::PrepareAsyncStreamDeviceEventsRaw(::grpc::ClientContext* context, const ::snowowl::StreamDeviceEventsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::snowowl::DeviceEvent>::Create(channel_.get(), cq, rpcmethod_StreamDeviceEvents_, context, request, false, nullptr);
}

DeviceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::snowowl::ListDevicesRequest, ::snowowl::ListDevicesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::ListDevicesRequest* req,
             ::snowowl::ListDevicesResponse* resp) {
               return service->ListDevices(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::snowowl::GetDeviceRequest, ::snowowl::GetDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::GetDeviceRequest* req,
             ::snowowl::GetDeviceResponse* resp) {
               return service->GetDevice(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::snowowl::CreateDeviceRequest, ::snowowl::CreateDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::CreateDeviceRequest* req,
             ::snowowl::CreateDeviceResponse* resp) {
               return service->CreateDevice(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::snowowl::UpdateDeviceRequest, ::snowowl::UpdateDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::UpdateDeviceRequest* req,
             ::snowowl::UpdateDeviceResponse* resp) {
               return service->UpdateDevice(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceService::Service, ::snowowl::DeleteDeviceRequest, ::snowowl::DeleteDeviceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::DeleteDeviceRequest* req,
             ::snowowl::DeleteDeviceResponse* resp) {
               return service->DeleteDevice(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< DeviceService::Service, ::snowowl::StreamDeviceEventsRequest, ::snowowl::DeviceEvent>(
          [](DeviceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::StreamDeviceEventsRequest* req,
             ::grpc::ServerWriter<::snowowl::DeviceEvent>* writer) {
               return service->StreamDeviceEvents(ctx, req, writer);
             }, this)));
}

DeviceService::Service::~Service() {
}

::grpc::Status DeviceService::Service::ListDevices(::grpc::ServerContext* context, const ::snowowl::ListDevicesRequest* request, ::snowowl::ListDevicesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::GetDevice(::grpc::ServerContext* context, const ::snowowl::GetDeviceRequest* request, ::snowowl::GetDeviceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::CreateDevice(::grpc::ServerContext* context, const ::snowowl::CreateDeviceRequest* request, ::snowowl::CreateDeviceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::UpdateDevice(::grpc::ServerContext* context, const ::snowowl::UpdateDeviceRequest* request, ::snowowl::UpdateDeviceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::DeleteDevice(::grpc::ServerContext* context, const ::snowowl::DeleteDeviceRequest* request, ::snowowl::DeleteDeviceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceService::Service::StreamDeviceEvents(::grpc::ServerContext* context, const ::snowowl::StreamDeviceEventsRequest* request, ::grpc::ServerWriter< ::snowowl::DeviceEvent>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* StreamService_method_names[] = {
  "/snowowl.StreamService/GetStreamInfo",
  "/snowowl.StreamService/ControlStream",
  "/snowowl.StreamService/StreamVideo",
};

std::unique_ptr< StreamService::Stub> StreamService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StreamService::Stub> stub(new StreamService::Stub(channel, options));
  return stub;
}

StreamService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetStreamInfo_(StreamService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ControlStream_(StreamService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamVideo_(StreamService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status StreamService::Stub::GetStreamInfo(::grpc::ClientContext* context, const ::snowowl::GetStreamInfoRequest& request, ::snowowl::GetStreamInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snowowl::GetStreamInfoRequest, ::snowowl::GetStreamInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStreamInfo_, context, request, response);
}

void StreamService::Stub::async::GetStreamInfo(::grpc::ClientContext* context, const ::snowowl::GetStreamInfoRequest* request, ::snowowl::GetStreamInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snowowl::GetStreamInfoRequest, ::snowowl::GetStreamInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStreamInfo_, context, request, response, std::move(f));
}

void StreamService::Stub::async::GetStreamInfo(::grpc::ClientContext* context, const ::snowowl::GetStreamInfoRequest* request, ::snowowl::GetStreamInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStreamInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snowowl::GetStreamInfoResponse>* StreamService::Stub::PrepareAsyncGetStreamInfoRaw(::grpc::ClientContext* context, const ::snowowl::GetStreamInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snowowl::GetStreamInfoResponse, ::snowowl::GetStreamInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStreamInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snowowl::GetStreamInfoResponse>* StreamService::Stub::AsyncGetStreamInfoRaw(::grpc::ClientContext* context, const ::snowowl::GetStreamInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStreamInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StreamService::Stub::ControlStream(::grpc::ClientContext* context, const ::snowowl::ControlStreamRequest& request, ::snowowl::ControlStreamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snowowl::ControlStreamRequest, ::snowowl::ControlStreamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ControlStream_, context, request, response);
}

void StreamService::Stub::async::ControlStream(::grpc::ClientContext* context, const ::snowowl::ControlStreamRequest* request, ::snowowl::ControlStreamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snowowl::ControlStreamRequest, ::snowowl::ControlStreamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ControlStream_, context, request, response, std::move(f));
}

void StreamService::Stub::async::ControlStream(::grpc::ClientContext* context, const ::snowowl::ControlStreamRequest* request, ::snowowl::ControlStreamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ControlStream_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snowowl::ControlStreamResponse>* StreamService::Stub::PrepareAsyncControlStreamRaw(::grpc::ClientContext* context, const ::snowowl::ControlStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snowowl::ControlStreamResponse, ::snowowl::ControlStreamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ControlStream_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snowowl::ControlStreamResponse>* StreamService::Stub::AsyncControlStreamRaw(::grpc::ClientContext* context, const ::snowowl::ControlStreamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncControlStreamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::snowowl::VideoFrame, ::snowowl::VideoFrameAck>* StreamService::Stub::StreamVideoRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::snowowl::VideoFrame, ::snowowl::VideoFrameAck>::Create(channel_.get(), rpcmethod_StreamVideo_, context);
}

void StreamService::Stub::async::StreamVideo(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::snowowl::VideoFrame,::snowowl::VideoFrameAck>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::snowowl::VideoFrame,::snowowl::VideoFrameAck>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamVideo_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::snowowl::VideoFrame, ::snowowl::VideoFrameAck>* StreamService::Stub::AsyncStreamVideoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::snowowl::VideoFrame, ::snowowl::VideoFrameAck>::Create(channel_.get(), cq, rpcmethod_StreamVideo_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::snowowl::VideoFrame, ::snowowl::VideoFrameAck>* StreamService::Stub::PrepareAsyncStreamVideoRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::snowowl::VideoFrame, ::snowowl::VideoFrameAck>::Create(channel_.get(), cq, rpcmethod_StreamVideo_, context, false, nullptr);
}

StreamService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamService::Service, ::snowowl::GetStreamInfoRequest, ::snowowl::GetStreamInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::GetStreamInfoRequest* req,
             ::snowowl::GetStreamInfoResponse* resp) {
               return service->GetStreamInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StreamService::Service, ::snowowl::ControlStreamRequest, ::snowowl::ControlStreamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StreamService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::ControlStreamRequest* req,
             ::snowowl::ControlStreamResponse* resp) {
               return service->ControlStream(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamService_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< StreamService::Service, ::snowowl::VideoFrame, ::snowowl::VideoFrameAck>(
          [](StreamService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::snowowl::VideoFrameAck,
             ::snowowl::VideoFrame>* stream) {
               return service->StreamVideo(ctx, stream);
             }, this)));
}

StreamService::Service::~Service() {
}

::grpc::Status StreamService::Service::GetStreamInfo(::grpc::ServerContext* context, const ::snowowl::GetStreamInfoRequest* request, ::snowowl::GetStreamInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamService::Service::ControlStream(::grpc::ServerContext* context, const ::snowowl::ControlStreamRequest* request, ::snowowl::ControlStreamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StreamService::Service::StreamVideo(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::snowowl::VideoFrameAck, ::snowowl::VideoFrame>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* MonitoringService_method_names[] = {
  "/snowowl.MonitoringService/GetRealTimeParams",
  "/snowowl.MonitoringService/StreamRealTimeParams",
};

std::unique_ptr< MonitoringService::Stub> MonitoringService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MonitoringService::Stub> stub(new MonitoringService::Stub(channel, options));
  return stub;
}

MonitoringService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetRealTimeParams_(MonitoringService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamRealTimeParams_(MonitoringService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status MonitoringService::Stub::GetRealTimeParams(::grpc::ClientContext* context, const ::snowowl::GetRealTimeParamsRequest& request, ::snowowl::GetRealTimeParamsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::snowowl::GetRealTimeParamsRequest, ::snowowl::GetRealTimeParamsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRealTimeParams_, context, request, response);
}

void MonitoringService::Stub::async::GetRealTimeParams(::grpc::ClientContext* context, const ::snowowl::GetRealTimeParamsRequest* request, ::snowowl::GetRealTimeParamsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::snowowl::GetRealTimeParamsRequest, ::snowowl::GetRealTimeParamsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRealTimeParams_, context, request, response, std::move(f));
}

void MonitoringService::Stub::async::GetRealTimeParams(::grpc::ClientContext* context, const ::snowowl::GetRealTimeParamsRequest* request, ::snowowl::GetRealTimeParamsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRealTimeParams_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::snowowl::GetRealTimeParamsResponse>* MonitoringService::Stub::PrepareAsyncGetRealTimeParamsRaw(::grpc::ClientContext* context, const ::snowowl::GetRealTimeParamsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::snowowl::GetRealTimeParamsResponse, ::snowowl::GetRealTimeParamsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRealTimeParams_, context, request);
}

::grpc::ClientAsyncResponseReader< ::snowowl::GetRealTimeParamsResponse>* MonitoringService::Stub::AsyncGetRealTimeParamsRaw(::grpc::ClientContext* context, const ::snowowl::GetRealTimeParamsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRealTimeParamsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::snowowl::RealTimeParamUpdate>* MonitoringService::Stub::StreamRealTimeParamsRaw(::grpc::ClientContext* context, const ::snowowl::StreamRealTimeParamsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::snowowl::RealTimeParamUpdate>::Create(channel_.get(), rpcmethod_StreamRealTimeParams_, context, request);
}

void MonitoringService::Stub::async::StreamRealTimeParams(::grpc::ClientContext* context, const ::snowowl::StreamRealTimeParamsRequest* request, ::grpc::ClientReadReactor< ::snowowl::RealTimeParamUpdate>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::snowowl::RealTimeParamUpdate>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamRealTimeParams_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::snowowl::RealTimeParamUpdate>* MonitoringService::Stub::AsyncStreamRealTimeParamsRaw(::grpc::ClientContext* context, const ::snowowl::StreamRealTimeParamsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::snowowl::RealTimeParamUpdate>::Create(channel_.get(), cq, rpcmethod_StreamRealTimeParams_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::snowowl::RealTimeParamUpdate>* MonitoringService::Stub::PrepareAsyncStreamRealTimeParamsRaw(::grpc::ClientContext* context, const ::snowowl::StreamRealTimeParamsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::snowowl::RealTimeParamUpdate>::Create(channel_.get(), cq, rpcmethod_StreamRealTimeParams_, context, request, false, nullptr);
}

MonitoringService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MonitoringService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MonitoringService::Service, ::snowowl::GetRealTimeParamsRequest, ::snowowl::GetRealTimeParamsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MonitoringService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::GetRealTimeParamsRequest* req,
             ::snowowl::GetRealTimeParamsResponse* resp) {
               return service->GetRealTimeParams(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MonitoringService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MonitoringService::Service, ::snowowl::StreamRealTimeParamsRequest, ::snowowl::RealTimeParamUpdate>(
          [](MonitoringService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::snowowl::StreamRealTimeParamsRequest* req,
             ::grpc::ServerWriter<::snowowl::RealTimeParamUpdate>* writer) {
               return service->StreamRealTimeParams(ctx, req, writer);
             }, this)));
}

MonitoringService::Service::~Service() {
}

::grpc::Status MonitoringService::Service::GetRealTimeParams(::grpc::ServerContext* context, const ::snowowl::GetRealTimeParamsRequest* request, ::snowowl::GetRealTimeParamsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MonitoringService::Service::StreamRealTimeParams(::grpc::ServerContext* context, const ::snowowl::StreamRealTimeParamsRequest* request, ::grpc::ServerWriter< ::snowowl::RealTimeParamUpdate>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace snowowl
#include <grpcpp/ports_undef.inc>

